# Generated by Django 4.1.2 on 2022-10-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="descriprion",
            new_name="description",
        ),
    ]
