# Generated by Django 4.1.2 on 2022-10-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="img",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(null=True, upload_to="portfolio/images/"),
        ),
    ]
